global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'registry-server'
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'prom123'
    static_configs:
      - targets: ['registry-server:4999']

  - job_name: 'config-server'
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'config'
      password: 'pass'
    static_configs:
      - targets: ['config-server:4998']

  - job_name: 'api-gateway'
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:5000']

  - job_name: 'auth-service'
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:5001']

  - job_name: 'controlplane-service'
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['controlplane-service:5002']

  - job_name: 'sdk-service'
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sdk-service:5003']
