# ===================================================================
# REGISTRY SERVER CONFIGURATION (application.yml)
# ===================================================================

# ===================================================================
# Server Settings
# ===================================================================
server:
  port: 4999

# ===================================================================
# Spring Settings
# ===================================================================
spring:
  profiles:
    active: dev-registryserver
  application:
    name: RegistryServer

# ===================================================================
# Eureka Server/Client Configuration
# ===================================================================
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:4999/eureka/}
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000

# ===================================================================
# Management & Actuator Endpoints Configuration
# ===================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: RegistryServer
  prometheus:
    metrics:
      export:
        enabled: true
