package com.rollout.io.server.controlplaneservice.controllers;

import com.rollout.io.server.controlplaneservice.entity.AuditLog;
import com.rollout.io.server.controlplaneservice.helpers.ApiResponseBuilder;
import com.rollout.io.server.controlplaneservice.objects.ApiResponse;
import com.rollout.io.server.controlplaneservice.service.AuditLogService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * REST Controller responsible for retrieving and exposing Event/Audit Logs.
 * Allows workspace administrators to monitor mutations and lifecycle events.
 */
@RestController
@RequestMapping("/api/v1/environments/{environmentId}/audit-logs")
@RequiredArgsConstructor
@Tag(name = "Audit Logs", description = "Endpoints for fetching environment level event and mutation logs")
public class AuditLogController {

    private final AuditLogService auditLogService;

    @GetMapping
    @Operation(summary = "Get Audit Logs", description = "Retrieves all audit logs generated by resource modifications within an environment.")
    public ResponseEntity<ApiResponse<List<AuditLog>>> getAuditLogs(
            @PathVariable String environmentId
    ) {
        // Assume minimal environment access validation could occur here or within service layer 
        // using environmentService if strict read checking is needed.
        return ApiResponseBuilder.out(
                HttpStatus.OK, 
                "Audit logs fetched successfully", 
                auditLogService.getEnvironmentAuditLogs(environmentId)
        );
    }
}
